### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by Lucky97** [iojw/socialscan#18]
socialscan --proxy-list proxy_list.txt --platforms tumblr  --input 100_queries.txt  --view-by platform
Traceback (most recent call last):
  File "C:\Users\Lucky\AppData\Local\Programs\Python\Python37\Scripts\socialscan-script.py", line 11, in <module>
    load_entry_point('socialscan==1.1.6', 'console_scripts', 'socialscan')()
  File "c:\users\lucky\appdata\local\programs\python\python37\lib\site-packages\socialscan\__main__.py", line 21, in main
    asyncio.run(cli.main())
  File "c:\users\lucky\appdata\local\programs\python\python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "c:\users\lucky\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "c:\users\lucky\appdata\local\programs\python\python37\lib\site-packages\socialscan\cli.py", line 70, in main
    with open(args.proxy_list, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'proxy_list.txt'

**Comment by iojw** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: 'proxy_list.txt'`

The file you’re referencing can’t be found. Make sure that the name is correct and that you’re in the correct directory.

**Comment by Lucky97** [comment]
yeah i have correct directory how can i fix?

**Comment by iojw** [comment]
The error is thrown because the tool can't find the file. Make sure that you're in the same directory as the file and have the correct name entered.

**Comment by Lucky97** [comment]
i'm in same directory  i entered correct name

**Comment by iojw** [comment]
You are either in the wrong directory or entering the wrong file name. The proxy-list option for the tool is currently working.

**Comment by Lucky97** [comment]
can you please send sample command  for this tool ?

**Comment by iojw** [comment]
`socialscan YOUR_USERNAME your@email.com`. You can run `—help` for explanations of all the options. Closing this issue.
