### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by MatteoTomasini** [iojw/socialscan#2]
script completes but get get exception ignored in  <function _ProactorBasePipeTransport.__del__ at 0x0000026C701C83C0> with RuntimeError: Event loop is closed

**Comment by iojw** [comment]
Could you provide more details about the command executed and the output from the tool?

**Comment by MatteoTomasini** [comment]
Issue when run from command line as provided in usage examples and when importing library also as shown in documentation

`Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001FA2DAD21C0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 95, in __del__
    self.close()
  File "C:\Python38\lib\asyncio\proactor_events.py", line 87, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python38\lib\asyncio\base_events.py", line 692, in call_soon
    self._check_closed()
  File "C:\Python38\lib\asyncio\base_events.py", line 485, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001FA2DAD21C0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 95, in __del__
    self.close()
  File "C:\Python38\lib\asyncio\proactor_events.py", line 87, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python38\lib\asyncio\base_events.py", line 692, in call_soon
    self._check_closed()
  File "C:\Python38\lib\asyncio\base_events.py", line 485, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001FA2DAD21C0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 95, in __del__
    self.close()
  File "C:\Python38\lib\asyncio\proactor_events.py", line 87, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python38\lib\asyncio\base_events.py", line 692, in call_soon
    self._check_closed()
  File "C:\Python38\lib\asyncio\base_events.py", line 485, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001FA2DAD21C0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 95, in __del__
    self.close()
  File "C:\Python38\lib\asyncio\proactor_events.py", line 87, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python38\lib\asyncio\base_events.py", line 692, in call_soon
    self._check_closed()
  File "C:\Python38\lib\asyncio\base_events.py", line 485, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed`

**Comment by iojw** [comment]
Hi, you're using a pre-release version of Python (3.8), and this looks to be an issue with the changes in the async event loop. Since there are likely to be many more changes to 3.8, I suggest you use the stable Python 3.7 to run the script instead.

**Comment by MatteoTomasini** [comment]
no issues with 3.7, thanks and great job with this library!

**Comment by leszekhanusz** [comment]
Looks to be [this bug](https://github.com/aio-libs/aiohttp/issues/4324)
