### ISSUE TITLE
KeyError: 'elapsed_s'

### ISSUE THREAD

**Issue by soumendrak** [iojw/socialscan#3]
Python 3.7  
Windows OS
```
C:\Users\soumendra>socialscan username-2 email74@gmail.com
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\socialscan.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\socialscan\__main__.py", line 7, in main
    asyncio.run(cli.main())
  File "c:\programdata\anaconda3\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "c:\programdata\anaconda3\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "c:\programdata\anaconda3\lib\site-packages\socialscan\cli.py", line 86, in main
    for future in tqdm.tqdm(asyncio.as_completed(platform_queries), total=len(platform_queries), disable=args.verbose, leave=False, ncols=BAR_WIDTH, bar_format=BAR_FORMAT):
  File "c:\programdata\anaconda3\lib\site-packages\tqdm\_tqdm.py", line 866, in __init__
    self.sp(self.__repr__(elapsed=0))
  File "c:\programdata\anaconda3\lib\site-packages\tqdm\_tqdm.py", line 898, in __repr__
    self.bar_format, self.postfix, self.unit_divisor)
  File "c:\programdata\anaconda3\lib\site-packages\tqdm\_tqdm.py", line 359, in format_meter
    r_bar = r_bar_user.format(**bar_args)
KeyError: 'elapsed_s'
Exception ignored in: <function tqdm.__del__ at 0x000001D0B4244D90>
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\tqdm\_tqdm.py", line 889, in __del__
  File "c:\programdata\anaconda3\lib\site-packages\tqdm\_tqdm.py", line 1095, in close
  File "c:\programdata\anaconda3\lib\site-packages\tqdm\_tqdm.py", line 441, in _decr_instances
  File "c:\programdata\anaconda3\lib\_weakrefset.py", line 109, in remove
KeyError: <weakref at 0x000001D0B3767458; to 'tqdm' at 0x000001D0B42B32B0>
sys:1: RuntimeWarning: coroutine 'query' was never awaited
```

**Comment by iojw** [comment]
This is due to the tqdm package not being updated on the system. The 'elapsed_s'  var was added in v4.31.0 (https://github.com/tqdm/tqdm/releases/tag/v4.31.0)

**Comment by soumendrak** [comment]
yes, it was `tqdm` issue.
By upgrading tqdm with `pip install -U tqdm` command, solved the issue.
You may close this issue. Thanks.
